In [16]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, lil_matrix
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix
from scipy.sparse.linalg import inv, eigs
import math

In [17]:
math.cos(math.pi)

-1.0

In [42]:
l=1.0
a=1.0
A = [[l*math.cos(math.pi*5/6), l*math.sin(math.pi*5/6), a],
     [l*math.cos(math.pi*3/2), l*math.sin(math.pi*3/2), a],
     [l*math.cos(math.pi*1/6), l*math.sin(math.pi*1/6), a]]

B = [[2/(3*l)*math.cos(math.pi*5/6), 2/(3*l)*math.cos(math.pi*3/2), 2/(3*l)*math.cos(math.pi*1/6)],
     [2/(3*l)*math.sin(math.pi*5/6), 2/(3*l)*math.sin(math.pi*3/2), 2/(3*l)*math.sin(math.pi*1/6)],
     [1/(3*a), 1/(3*a), 1/(3*a)]]

csc_a = csc_matrix(A)
csc_b = csc_matrix(B)

# csr_inv = linalg.inv(csr)
# SparseEfficiencyWarning: splu requires CSC matrix format
# SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format

# csc_inv = inv(csc)
print((csc_a*csc_b).toarray())


[[ 1.00000000e+00  1.66533454e-16 -5.55111512e-17]
 [ 1.66533454e-16  1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17 -5.55111512e-17  1.00000000e+00]]


In [31]:
print(math.cos(math.pi*5/6), math.sin(math.pi*5/6))
print(math.cos(math.pi*3/2), math.sin(math.pi*3/2))
print(math.cos(math.pi*1/6), math.sin(math.pi*1/6))

-0.8660254037844387 0.49999999999999994
-1.8369701987210297e-16 -1.0
0.8660254037844387 0.49999999999999994


In [40]:
math.cos(math.pi/6)*2/3

0.5773502691896258